version: '3.8'
services:
  postgresql:
    container_name: web-crawler
    image: bitnami/postgresql:latest
    ports:
      - "5431:5431"
    environment:
      POSTGRESQL_USERNAME: webcrawler
      POSTGRESQL_PASSWORD: password123
      POSTGRESQL_DATABASE: pgdb
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"