### https://www.enki.com | https://code.visualstudio.com | https://fastify.dev
### @baseUrl = https://  http://localhost:3000
@baseUrl = https://project-web-crawler-production.up.railway.app/

### Post
POST {{baseUrl}}/domain
Content-Type: application/json

{
  "domain":"https://www.enki.com"
}

### @queue
GET {{baseUrl}}/queue

### @tree
GET {{baseUrl}}/tree

### @treeascii
GET {{baseUrl}}/tree/ascii

### @nodes
GET {{baseUrl}}/nodes

### @/nodes/:url
GET {{baseUrl}}/nodes/:url