@baseUrl = http://localhost:3000

# @name sendURL
POST http://localhost:3000/domain
Content-Type: application/json

{
  "dominio": "https://brunosduarte.dev.br"
}


# @queue
GET {{baseUrl}}/queue

# @tree
GET {{baseUrl}}/tree

# @treeascii
GET {{baseUrl}}/tree/ascii