@baseUrlLocal = http://localhost:3000/
@baseUrl = https://server-twva7shmeq-uc.a.run.app/

### Post
POST {{baseUrl}}/domain
Content-Type: application/json

{
  "domain":"https://www.enki.com/"
}

### @queue
GET {{baseUrl}}/queue

### @tree
GET {{baseUrl}}/tree

### @treeascii
GET {{baseUrl}}/tree/ascii