@baseUrl = http://localhost:3000

# @name sendURL
POST {{baseUrl}}/domain
Content-Type: application/json

{
  "testando": "https://brunosduarte.dev.br",
}


# @queue
GET {{baseUrl}}/queue

# @tree
GET {{baseUrl}}/tree

# @treeascii
GET {{baseUrl}}/tree/ascii