name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push image to Amazon ECR
      run: |
        cd server
        docker build -t $ECR_REPOSITORY:$GITHUB_SHA .
        docker push $ECR_REPOSITORY:$GITHUB_SHA

    - name: Fill in the new image ID in the ECS task definition
      id: latest
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: site-mapper-1-task.json
        container-name: site-mapper-1-container
        image: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        service: site-mapper-1-deploy
        cluster: site-mapper-1
        task-definition: ${{ steps.task-def.outputs.task-definition }}
